# Dockerfile.ec_de
FROM python:3.9-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos necesarios para el Digital Engine
COPY requirements.txt .

# Instalar las dependencias necesarias (Kafka, sockets, etc.)
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente de EC_DE al contenedor
COPY ./src/taxi/ec_de.py /app

# Exponer el puerto necesario para los sockets (con EC_Central)
EXPOSE 8080