# Usar una imagen de Python
FROM python:3.9-slim

# Establecer directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de requisitos de la central
COPY requirements.txt .

# Instalar las dependencias
RUN pip install -r requirements.txt

# Copiar el código de la central al contenedor
COPY src/central/ .

# Exponer un puerto si es necesario (opcional, puede ser eliminado si no es relevante)
EXPOSE 5000

# Comando para ejecutar la central
CMD ["python", "ec_central.py"]
