FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/customer ./customer
COPY src/common ./common

CMD ["python", "-m", "customer.ec_customer"]