# Usar imagen base de Python
FROM python:3.9-slim

# Crear un directorio de trabajo
WORKDIR /app

# Copiar todos los archivos al contenedor
COPY ./src/taxi /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Establecer variables de entorno necesarias, como la IP del Digital Engine
ENV DIGITAL_ENGINE_HOST=digital_engine

# Ejecutar la aplicación
CMD ["python", "sensors.py"]