# Usar imagen base de Python
FROM python:3.9-slim

# Crear un directorio de trabajo
WORKDIR /app

# Copiar todos los archivos al contenedor
COPY ./src/customer /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./kafka_certs ./kafka_certs

# Comando para ejecutar el cliente
CMD ["python", "ec_customer.py"]
