# Dockerfile.ec_s
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app


# Copiar los archivos necesarios para el Digital Engine
COPY requirements.txt .

# Instalar las dependencias necesarias (Kafka, sockets, etc.)
RUN pip install --no-cache-dir -r requirements.txt

# Copiar los archivos necesarios para el Sensor
COPY ./src/taxi/ec_s.py /app

# Exponer el puerto necesario para la comunicación con EC_DE
EXPOSE 7070