# Usar una imagen de Python
FROM python:3.9-slim

# Establecer directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de requisitos de los taxis
COPY src/taxi/requirements.txt .

# Instalar las dependencias
RUN pip install -r requirements.txt

# Copiar el código del taxi al contenedor
COPY src/taxi/ .

# Exponer un puerto si es necesario (opcional, puede ser eliminado si no es relevante)
EXPOSE 5001

# Comando para ejecutar los taxis
CMD ["python", "ec_taxi.py"]
