# Usar imagen base de Python
FROM python:3.9-slim

# Crear un directorio de trabajo
WORKDIR /app

# Copiar todos los archivos al contenedor
COPY ./src/taxi /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Comando para ejecutar el EC_DE.py (ajusta según tus necesidades)
CMD ["python", "ec_de.py", "localhost", "5555", "localhost:9092", "localhost", "6000", "1"]
