# Usar imagen base de Python
FROM python:3.9-slim

# Crear un directorio de trabajo
WORKDIR /app

# Copiar todos los archivos al contenedor
COPY ./src/taxi /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV KAFKA_BOOTSTRAP_SERVERS=kafka:9092
ENV CENTRAL_HOST=central
ENV TAXI_ID=1